### ISSUE TITLE
make simple fits js reader

### ISSUE THREAD

**Issue by volodymyrss** [esg-epfl-apc/astrojsvis#2]
this lib will not do visualization, but produce json

if we like this http://astrojs.github.io/fitsjs/, https://github.com/astrojs/fitsjs we can maintain fork https://github.com/esg-epfl-apc/fitsjs

separately check why aladinlite uses webassembly with rust to read fits

if we want a much simpler library, then put it into this repo, and add a readme about the alternatives we considred

**Comment by francoismg** [comment]
Regarding the use of fits.js (as discussed in previous meeting) : 

The main issue with this library (besides the fact that it has not been maintained in 10 years) is that it was written with CoffeeScript which while still being somewhat under development (last version is from 2022) is almost not used anymore and thus has a very small user base. TypeScript and ES6 have addressed most of the issues CoffeeScript was built to fix rendering it useless in the modern js ecosystem.

Also the CoffeeScript version used is also old and predates ES6 and several additions to the language thus the transpiled js produced by the library relies heavily on prototype and other old js features which makes it not suitable for an integration into a more modern codebase.

Since the transpiled js produced by CoffeeScript is rather clean and readable one proposed solution was too migrate to the latest version of CoffeeScript (which supports ES6 features) and then refactor the resulting js code to create a standalone library without the reliance on CoffeeScript.

This solution has several drawbacks since it is not clear what amount of effort would be needed to migrate the sources and possibly cakefile to the latest version (a few breaking changes have been introduced between 1.x and 2.x) also there's no guarantee that the output could be easily refactored into a standalone library.

The proposed solution was rejected during the meeting for a lack of resources needed in order to maintain the library.

Summary : 

- fits.js relies on CoffeeScript which makes it not suitable for a modern codebase and environment
- The CoffeeScript version is old and does not support any modern javascript features
- The library would have to be migrated from 1.6 to CoffeeScript2 and it's hard to estimate the amount of effort needed
- A solution would be to migrate to 2.x and use the resulting js code to start a new library but there are uncertainties about the viability of the js output and the work needed to refactor it into a standalone library
- Proposed solution was rejected because of the amount of resource needed to maintain it

**Comment by francoismg** [comment]
Fits reader prototype seems to be working with binary table file at least standard ones (primary header without data followed by binary table headers with one table group)

TODO:
- check with more files to find bugs and edge cases
- fix formatting for header properties
- add conversion of header data to json, csv
- add support for primary header with data
- add support for ascii table and image
- add support for multiple dataset for the same header (GCOUNT header property)

**Comment by francoismg** [comment]
Migrated fits.js (coffeescript 1.6.3 to 2.7.0 to standard js) is available here :

https://github.com/esg-epfl-apc/astrojsvis/blob/main/prototypes/coffeescript_fitsjs/fits.js

**Comment by francoismg** [comment]
> Migrated fits.js (coffeescript 1.6.3 to 2.7.0 to standard js) is available here :
> 
> https://github.com/esg-epfl-apc/astrojsvis/blob/main/prototypes/coffeescript_fitsjs/fits.js

The main bugs from the migration and library breakdown seem to be fixed now.

The broke down library is working (at least for images and binary tables), need some more refactor but overall seems to be ok

**Comment by volodymyrss** [comment]
> > Migrated fits.js (coffeescript 1.6.3 to 2.7.0 to standard js) is available here :
> > https://github.com/esg-epfl-apc/astrojsvis/blob/main/prototypes/coffeescript_fitsjs/fits.js
> 
> The main bugs from the migration and library breakdown seem to be fixed now.
> 
> The broke down library is working (at least for images and binary tables), need some more refactor but overall seems to be ok

Ok, thanks, so you can also use it in the gh-page?

**Comment by francoismg** [comment]
> > > Migrated fits.js (coffeescript 1.6.3 to 2.7.0 to standard js) is available here :
> > > https://github.com/esg-epfl-apc/astrojsvis/blob/main/prototypes/coffeescript_fitsjs/fits.js
> > 
> > 
> > The main bugs from the migration and library breakdown seem to be fixed now.
> > The broke down library is working (at least for images and binary tables), need some more refactor but overall seems to be ok
> 
> Ok, thanks, so you can also use it in the gh-page?

yea sure will add that too, maybe I can link that with the graph so it will integrate all the components in the same demo
